
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482311039
 */
public class JFrameInicial extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInicial
     */
    public JFrameInicial() {
        initComponents();
    }
    
    /* public TelaCalculadora(){
        initComponents();
    }*/
    double valor1, valor2;
    String operacao;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClique = new javax.swing.JButton();
        btnnum1 = new javax.swing.JButton();
        btnnum2 = new javax.swing.JButton();
        btnnum3 = new javax.swing.JButton();
        btnnum4 = new javax.swing.JButton();
        btnnum5 = new javax.swing.JButton();
        btnnum6 = new javax.swing.JButton();
        btnnum7 = new javax.swing.JButton();
        btnnum8 = new javax.swing.JButton();
        btnnum9 = new javax.swing.JButton();
        btnnum0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnsoma = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btndividir = new javax.swing.JButton();
        btnmult = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnigual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClique.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnClique.setForeground(new java.awt.Color(20, 223, 40));
        btnClique.setText("Clique em mim!");
        btnClique.setName(""); // NOI18N
        btnClique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliqueActionPerformed(evt);
            }
        });

        btnnum1.setBackground(new java.awt.Color(153, 255, 255));
        btnnum1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum1.setForeground(new java.awt.Color(255, 153, 255));
        btnnum1.setText("1");
        btnnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum1ActionPerformed(evt);
            }
        });

        btnnum2.setBackground(new java.awt.Color(153, 255, 255));
        btnnum2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum2.setForeground(new java.awt.Color(255, 153, 255));
        btnnum2.setText("2");
        btnnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum2ActionPerformed(evt);
            }
        });

        btnnum3.setBackground(new java.awt.Color(153, 255, 255));
        btnnum3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum3.setForeground(new java.awt.Color(255, 153, 255));
        btnnum3.setText("3");
        btnnum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum3ActionPerformed(evt);
            }
        });

        btnnum4.setBackground(new java.awt.Color(153, 255, 255));
        btnnum4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum4.setForeground(new java.awt.Color(255, 153, 255));
        btnnum4.setText("4");
        btnnum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum4ActionPerformed(evt);
            }
        });

        btnnum5.setBackground(new java.awt.Color(153, 255, 255));
        btnnum5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum5.setForeground(new java.awt.Color(255, 153, 255));
        btnnum5.setText("5");
        btnnum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum5ActionPerformed(evt);
            }
        });

        btnnum6.setBackground(new java.awt.Color(153, 255, 255));
        btnnum6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum6.setForeground(new java.awt.Color(255, 153, 255));
        btnnum6.setText("6");
        btnnum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum6ActionPerformed(evt);
            }
        });

        btnnum7.setBackground(new java.awt.Color(153, 255, 255));
        btnnum7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum7.setForeground(new java.awt.Color(255, 153, 255));
        btnnum7.setText("7");
        btnnum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum7ActionPerformed(evt);
            }
        });

        btnnum8.setBackground(new java.awt.Color(153, 255, 255));
        btnnum8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum8.setForeground(new java.awt.Color(255, 153, 255));
        btnnum8.setText("8");
        btnnum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum8ActionPerformed(evt);
            }
        });

        btnnum9.setBackground(new java.awt.Color(153, 255, 255));
        btnnum9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum9.setForeground(new java.awt.Color(255, 153, 255));
        btnnum9.setText("9");
        btnnum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum9ActionPerformed(evt);
            }
        });

        btnnum0.setBackground(new java.awt.Color(153, 255, 255));
        btnnum0.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnnum0.setForeground(new java.awt.Color(255, 153, 255));
        btnnum0.setText("0");
        btnnum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnum0ActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setForeground(new java.awt.Color(204, 204, 255));
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnsoma.setBackground(new java.awt.Color(153, 255, 255));
        btnsoma.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnsoma.setForeground(new java.awt.Color(255, 153, 255));
        btnsoma.setText("+");
        btnsoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsomaActionPerformed(evt);
            }
        });

        btnsub.setBackground(new java.awt.Color(153, 255, 255));
        btnsub.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnsub.setForeground(new java.awt.Color(255, 153, 255));
        btnsub.setText("-");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        btndividir.setBackground(new java.awt.Color(153, 255, 255));
        btndividir.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btndividir.setForeground(new java.awt.Color(255, 153, 255));
        btndividir.setText("/");
        btndividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndividirActionPerformed(evt);
            }
        });

        btnmult.setBackground(new java.awt.Color(153, 255, 255));
        btnmult.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnmult.setForeground(new java.awt.Color(255, 153, 255));
        btnmult.setText("*");
        btnmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        btnigual.setText("=");
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnum1)
                        .addGap(18, 18, 18)
                        .addComponent(btnnum2)
                        .addGap(18, 18, 18)
                        .addComponent(btnnum3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnum4)
                        .addGap(18, 18, 18)
                        .addComponent(btnnum5)
                        .addGap(18, 18, 18)
                        .addComponent(btnnum6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btndividir)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnsoma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnmult)
                            .addComponent(btnsub)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnnum7)
                    .addComponent(btnigual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnum8)
                        .addGap(18, 18, 18)
                        .addComponent(btnnum9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnum0)
                        .addGap(18, 18, 18)
                        .addComponent(btnClique))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsub)
                    .addComponent(btnsoma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndividir)
                    .addComponent(btnmult))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnum1)
                    .addComponent(btnnum2)
                    .addComponent(btnnum3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnum4)
                    .addComponent(btnnum5)
                    .addComponent(btnnum6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnum7)
                    .addComponent(btnnum8)
                    .addComponent(btnnum9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnum0)
                    .addComponent(btnClique)
                    .addComponent(btnigual))
                .addGap(302, 302, 302))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //funcionalidade do botão, e seu parâmetro demonstra o evento
    private void btnCliqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliqueActionPerformed
       JOptionPane.showMessageDialog(null,"Muito Obrigado!");
    }//GEN-LAST:event_btnCliqueActionPerformed

    private void btnnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum1ActionPerformed
       txtResultado.setText(txtResultado.getText()+"1");
    }//GEN-LAST:event_btnnum1ActionPerformed

    private void btnnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum2ActionPerformed
        txtResultado.setText(txtResultado.getText()+"2");
    }//GEN-LAST:event_btnnum2ActionPerformed

    private void btnnum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum3ActionPerformed
         txtResultado.setText(txtResultado.getText()+"3");
    }//GEN-LAST:event_btnnum3ActionPerformed

    private void btnnum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum4ActionPerformed
        txtResultado.setText(txtResultado.getText()+"4");
    }//GEN-LAST:event_btnnum4ActionPerformed

    private void btnnum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum5ActionPerformed
       txtResultado.setText(txtResultado.getText()+"5");
    }//GEN-LAST:event_btnnum5ActionPerformed

    private void btnnum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum6ActionPerformed
        txtResultado.setText(txtResultado.getText()+"6");
    }//GEN-LAST:event_btnnum6ActionPerformed

    private void btnnum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum7ActionPerformed
        txtResultado.setText(txtResultado.getText()+"7");
    }//GEN-LAST:event_btnnum7ActionPerformed

    private void btnnum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum8ActionPerformed
        txtResultado.setText(txtResultado.getText()+"8");
    }//GEN-LAST:event_btnnum8ActionPerformed

    private void btnnum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum9ActionPerformed
        txtResultado.setText(txtResultado.getText()+"9");
    }//GEN-LAST:event_btnnum9ActionPerformed

    private void btnsomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsomaActionPerformed
        jLabel1.setText(txtResultado.getText());
        txtResultado.setText( "");
        
        valor1 = Double.parseDouble(jLabel1.getText());
        operacao = "soma";
    }//GEN-LAST:event_btnsomaActionPerformed

    private void btnnum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnum0ActionPerformed
         txtResultado.setText(txtResultado.getText()+"0");
    }//GEN-LAST:event_btnnum0ActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        double resultado;
        valor2 = Double.parseDouble(txtResultado.getText());
        if(operacao=="soma"){
            resultado = valor1 +valor2;
            jLabel1.setText (valor1+" + "+valor2+" = ");
            txtResultado.setText(String.valueOf(resultado));
        }
        else if(operacao=="sub"){
            resultado = valor1 - valor2;
            jLabel1.setText (valor1+" - "+valor2+" = ");
            txtResultado.setText(String.valueOf(resultado));
        }
        else if(operacao=="mult"){
            resultado = valor1 * valor2;
            jLabel1.setText (valor1+" * "+valor2+" = ");
            txtResultado.setText(String.valueOf(resultado));
        }
        else if(operacao=="dividir"){
            resultado = valor1 +valor2;
            jLabel1.setText (valor1+" / "+valor2+" = ");
            txtResultado.setText(String.valueOf(resultado));
        }
         //txtResultado.setText( "");
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        jLabel1.setText(txtResultado.getText());
        txtResultado.setText( " ");
        
        valor1 = Double.parseDouble(txtResultado.getText());
        operacao = "sub";
    }//GEN-LAST:event_btnsubActionPerformed

    private void btndividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndividirActionPerformed
        jLabel1.setText(txtResultado.getText());
        txtResultado.setText( " ");
        
        valor1 = Double.parseDouble(txtResultado.getText());
        operacao = "dividir";
    }//GEN-LAST:event_btndividirActionPerformed

    private void btnmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultActionPerformed
           jLabel1.setText(txtResultado.getText());
        txtResultado.setText( " ");
        
        valor1 = Double.parseDouble(txtResultado.getText());
        operacao = "mult";
    }//GEN-LAST:event_btnmultActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClique;
    private javax.swing.JButton btndividir;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnmult;
    private javax.swing.JButton btnnum0;
    private javax.swing.JButton btnnum1;
    private javax.swing.JButton btnnum2;
    private javax.swing.JButton btnnum3;
    private javax.swing.JButton btnnum4;
    private javax.swing.JButton btnnum5;
    private javax.swing.JButton btnnum6;
    private javax.swing.JButton btnnum7;
    private javax.swing.JButton btnnum8;
    private javax.swing.JButton btnnum9;
    private javax.swing.JButton btnsoma;
    private javax.swing.JButton btnsub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
